import sys
import os
from pathlib import Path
from datetime import date, datetime
from decimal import Decimal

# Add backend to path
backend_path = Path(__file__).parent.parent / "backend"
sys.path.append(str(backend_path))

from app.backtest.engine import OptionsBacktester
from app.backtest.config import BacktestConfig
from app.backtest.data_provider import UwdCsvDataProvider
from app.db.models import Base
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

def run_backtest():
    print("Setting up backtest...")
    
    # 1. Setup Data Provider
    data_dir = Path(__file__).parent.parent / "sample_data"
    provider = UwdCsvDataProvider(str(data_dir))
    
    # 2. Setup Database (In-memory for test)
    engine = create_engine("sqlite:///:memory:")
    Base.metadata.create_all(engine)
    SessionLocal = sessionmaker(bind=engine)
    db = SessionLocal()
    
    # 3. Configure Backtest
    # We only have data for 2025-12-24 in the sample
    config = BacktestConfig(
        start_date=date(2025, 12, 24),
        end_date=date(2025, 12, 24),
        initial_capital=100_000.0,
        strategy_name="Sample Data Test",
        underlying_filter=["SPY", "QQQ", "IWM"] # Filter to major ETFs to ensure we hit data
    )
    
    print(f"Running backtest for {config.start_date} to {config.end_date}...")
    
    # Verify data loading
    print("Verifying data access...")
    spy_quote = provider.get_underlying_quote("SPY", datetime(2025, 12, 24, 16, 0))
    if spy_quote:
        print(f"Found SPY data: Close=${spy_quote.close}")
    else:
        print("WARNING: Could not load SPY data!")
        
    # 4. Run Backtest
    backtester = OptionsBacktester(config, provider, db)
    results = backtester.run()
    
    # 5. Report Results
    print("\nBacktest Complete!")
    summary = results.performance_summary
    final_equity = float(config.initial_capital) + summary.get('total_pnl', 0.0)
    
    print(f"Final Equity: ${final_equity:,.2f}")
    print(f"Total Return: {summary.get('total_return_pct', 0.0):.2f}%")
    print(f"Trades: {summary.get('total_trades', 0)}")
    print(f"Win Rate: {summary.get('win_rate', 0.0) * 100:.2f}%")
    
    if summary.get('total_trades', 0) > 0:
        print("\nTrade Log:")
        for trade in results.trades:
            print(f"{trade.trade_date} {trade.underlying_symbol} {trade.strategy_name} -> P/L: ${trade.pnl_absolute:,.2f}")
    else:
        print("\nNo trades executed. This might be due to:")
        print("1. No signals generated by the strategy")
        print("2. Data missing for the specific underlyings")
        print("3. Strategy filters (regime, confidence) too strict")

if __name__ == "__main__":
    run_backtest()
